### ISSUE TITLE
Add chart data representation 

### ISSUE THREAD

**Issue by Proladge** [danbilokha/covid19liveupdates#18]
Add an option for user to see last time(In my opinion it should be a week) trends on the chart **within the country** and **globally**.
currently used data source https://pomber.github.io/covid19/timeseries.json seems to be suitable for it. 

The plan is to cosume api https://quickchart.io/
for generating pictures. It's just an option, feel free to choose another instrument.

**Comment by thomasnevins** [comment]
Could you have the bot tell you the change in cases for the area in the past 24 hours, past week, etc?

**Comment by danbilokha** [comment]
@thomasnevins It's possible
