### ISSUE TITLE
Add information of datasource used

### ISSUE THREAD

**Issue by danbilokha** [danbilokha/covid19liveupdates#47]
Provide information about 
1. data sources we're using
  - [x] In the description,
  - [x] In the `/help` message (should be visible on `/start` as well)
2. how often it updates

**Comment by thomasnevins** [comment]
What about this data set from the WHO? https://who.sprinklr.com/
And John Hopkins dataset has regional information for some of the larger countries

**Comment by danbilokha** [comment]
@thomasnevins thank you for the link, I haven't seen it. And I haven't know that John Hopkins provides country regions breakdown as well. That's really interesting, need to take a look into it.
