### ISSUE TITLE
Useful information

### ISSUE THREAD

**Issue by danbilokha** [danbilokha/covid19liveupdates#53]
Link to some videos which are good to explain how to prevent the contagious or other topics related to the coronavirus. The videos must tell the truth, be recognized and easy to understand

_thoughts_ As an option, it could be added to **advice** section

**Comment by thomasnevins** [comment]
Could you add a link to youtube?
https://youtu.be/d914EnpU4Fo

**Comment by thomasnevins** [comment]
As a second thought, this could be very tricky. Because people will be imitating the chat if different languages, and then they would need a corresponding video to that language

**Comment by danbilokha** [comment]
@thomasnevins the link is not a problem, I think we can have it. The second one will definitely be tricky, we haven't worked on it, yet. I deem we should postpone language differentiation for a while
