### ISSUE TITLE
Data Update

### ISSUE THREAD

**Issue by thomasnevins** [danbilokha/covid19liveupdates#57]
The data is not updating. 
There are 142696 cases today and yesterday. As I am writing this there are over 1500000 cases per John Hopkins

**Comment by danbilokha** [comment]
@thomasnevins do you think we need to do it in release 2? We have a lot of things to do, I am not sure we'd have the capacity for that

**Comment by thomasnevins** [comment]
Not needed for V2

**Comment by thomasnevins** [comment]
@danbilokha

**Comment by danbilokha** [comment]
@thomasnevins thanks!

**Comment by danbilokha** [comment]
Data is updated once\or twice a day, thus it's not a bug.
